# Base stage: Install dependencies
FROM node:20-alpine as base
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install

# Development stage: Run Vite dev server
FROM base as develop
WORKDIR /app
# This is the directory vite will use
COPY frontend/ ./
EXPOSE 5173
# Use --host to expose the server to other services in the docker network
CMD ["npm", "run", "dev", "--", "--host"]

# Production build stage
FROM base as build
WORKDIR /app
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
COPY frontend/ ./
RUN npm run build

# Production serve stage
FROM nginx:1.25-alpine
# Default nginx dockerfile uses this folder
WORKDIR /usr/share/nginx/html
# remove default nginx page
RUN rm ./*
COPY --from=build /app/dist .
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
